package rts.tiles;

import com.github.appreciated.material.MaterialTheme;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.server.ClassResource;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.BaseTheme;
import com.vaadin.ui.themes.ValoTheme;


public class HeaderUI extends CustomComponent {
	
	private static final long serialVersionUID = 3939337840850503423L;
	private AbsoluteLayout mainLayout = new AbsoluteLayout();
	private Panel headerPanel = new Panel();
	private VerticalLayout verticalLayout_1;
	private HorizontalLayout horizontalLayout_1;
	private HorizontalLayout verticalLayout_4;
	private Label label_user;
	private VerticalLayout verticalLayout_3;
	private Label label_name;
	private VerticalLayout verticalLayout_2;
    private Navigator navigator;
    private Link linkKKB;
    private CssLayout menu = new CssLayout();
    
    public HeaderUI(Navigator navigator) {
    	this.navigator = navigator;
    	this.setSizeFull();
    	
    	mainLayout.setImmediate(false);
    	mainLayout.setSizeFull();
    	
    	//panel_1
    	headerPanel.setImmediate(false);
    	headerPanel.setSizeFull();
    	
    	// verticalLayout_1
    	verticalLayout_1 = buildVerticalLayout_1();
    	headerPanel.setContent(verticalLayout_1);
    	mainLayout.addComponent(headerPanel, "top:0px; left:0.0px");
    	setCompositionRoot(mainLayout);
    }

	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth(100.0f, Unit.PERCENTAGE);
		verticalLayout_1.setMargin(false);
		
		//horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_1.addComponent(horizontalLayout_1);
		verticalLayout_1.setComponentAlignment(horizontalLayout_1,
				new Alignment(48));
		return verticalLayout_1;
	}

	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_1.addComponent(verticalLayout_2);
		horizontalLayout_1.setExpandRatio(verticalLayout_2, 1.0f);
		horizontalLayout_1.setComponentAlignment(verticalLayout_2,
				new Alignment(48));
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		horizontalLayout_1.addComponent(verticalLayout_3);
		horizontalLayout_1.setExpandRatio(verticalLayout_3, 1.0f);
		horizontalLayout_1.setComponentAlignment(verticalLayout_3, 
				new Alignment(48));
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		horizontalLayout_1.addComponent(verticalLayout_4);
		horizontalLayout_1.setExpandRatio(verticalLayout_4, 1.0f);
		horizontalLayout_1.setComponentAlignment(verticalLayout_4, Alignment.MIDDLE_RIGHT);
		return horizontalLayout_1;
	}
	
	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth(100.0f, Unit.PERCENTAGE);
		verticalLayout_2.setMargin(false);
		
		// Логотип банка 
		Image logout = new Image();
	    logout.setSource(new ThemeResource("img/logo-big.png"));
		logout.setWidth("245px");
		logout.setHeight("25px");  
		verticalLayout_2.addComponent(logout);
		verticalLayout_2.setSizeUndefined();
		verticalLayout_2.setSpacing(true);
		verticalLayout_2.setComponentAlignment(logout, Alignment.MIDDLE_LEFT);
		
	/*	linkKKB = new Link(null, new ExternalResource("http://www.kkb.kg"));
		linkKKB.setIcon(new ThemeResource("img/logo-big.png"));
		linkKKB.setWidth("135px");
		linkKKB.setHeight("18px");
		verticalLayout_2.addComponent(linkKKB);
		verticalLayout_2.setSizeUndefined();
		verticalLayout_2.setSpacing(true);
		verticalLayout_2.setComponentAlignment(linkKKB, Alignment.MIDDLE_LEFT);*/
		
		return verticalLayout_2;
	}
	
	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth(100.0f, Unit.PERCENTAGE);
		verticalLayout_3.setMargin(false);
		
		// label name
		label_name = new Label("Процесс регистрации операционных потерь");
	//	label_name.addStyleName("h4");
		label_name.setImmediate(false);
		label_name.setWidth("-1px");
		label_name.setHeight("-1px");
		label_name.addStyleName(ValoTheme.LABEL_COLORED);
		verticalLayout_3.addComponent(label_name);
		verticalLayout_3.setComponentAlignment(label_name, new Alignment(48));
		
		return verticalLayout_3;
	}
	
	private HorizontalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new HorizontalLayout();
		verticalLayout_4.setImmediate(true);
		verticalLayout_4.setWidth(100.0f, Unit.PERCENTAGE);
		verticalLayout_4.setMargin(false);
	
		// label_user
		label_user = new Label("<li><b> </b></li> ", ContentMode.HTML);
		label_user.setImmediate(false);
		label_user.setWidth("-1px");
		label_user.setHeight("-1px");
	
		try {
			label_user.setValue(UI.getCurrent().getSession().getAttribute("users_firstname").toString()+
					" "+ UI.getCurrent().getSession().getAttribute("users_surname").toString());
		} catch (Exception e) {
			System.out.println(e);
		}
		label_user.addStyleName(ValoTheme.LABEL_COLORED);
		verticalLayout_4.addComponent(label_user);
		verticalLayout_4.setComponentAlignment(label_user, Alignment.MIDDLE_RIGHT);
		
		// button for exit		
		Button logout = new Button("Выйти");
		logout.setHeight("33px");
		logout.addStyleName(ValoTheme.BUTTON_LINK);
		logout.setIcon(FontAwesome.SIGN_OUT);
								
		verticalLayout_4.addComponent(logout);
		verticalLayout_4.setSizeUndefined();
		verticalLayout_4.setSpacing(true);
		verticalLayout_4.setComponentAlignment(logout, Alignment.MIDDLE_RIGHT);
	
		logout.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -6193039844515992776L;
			@Override
			public void buttonClick(com.vaadin.ui.Button.ClickEvent event) {
				// TODO Auto-generated method stub
				UI.getCurrent().getSession().setAttribute("users_id", null);
				navigator.navigateTo("");				
			}
		});   
		
		return verticalLayout_4;
	}
}
